import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { AnimatedHero } from "@/components/AnimatedHero";
import styles from "@/styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <section className={styles.hero}>
          <hr />
          <AnimatedHero />
          <hr />
        </section>
        <section className={styles.about}>
          <p>
            I am a <span className={styles.emphasize}>software engineer</span>,
            enthusiastic and passionate about web development technologies.
          </p>
        </section>
      </section>
    </>
  );
}
